# Generated by Django 5.0.6 on 2024-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
