# Generated by Django 5.0.6 on 2024-06-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_bankaccount_name_alter_unit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='amount',
            new_name='balance',
        ),
    ]
