# Generated by Django 5.0.6 on 2024-06-15 20:24

import django.db.models.deletion
import purchases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_transfer_destination_balance_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit',
            field=models.ForeignKey(blank=True, default=purchases.models.get_default_unit, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='purchases.unit'),
        ),
    ]
